version: '3.5'
services:
  test_app:
    container_name: test_app
    image: test_app
    build:
      context: .
      dockerfile: deploy/Dockerfile
    volumes:
    - ./:/app
    tty: true
    stdin_open: true
