version: '3.5'
services:
  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    networks:
      - selenium_grid

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - selenium_grid


networks:
  selenium_grid:
    name: selenium